[program:exchange-worker-high]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /var/www/html/artisan queue:work redis --queue=high --sleep=3 --tries=3 --max-time=3600 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
stopwaitsecs=65
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:exchange-worker-default]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /var/www/html/artisan queue:work redis --queue=default --sleep=3 --tries=3 --max-time=3600 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
stopwaitsecs=65
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:exchange-worker-batch]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /var/www/html/artisan queue:work redis --queue=batch-matching --sleep=5 --tries=3 --max-time=3600 --timeout=300
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
stopwaitsecs=65
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[group:exchange-workers]
programs=exchange-worker-high,exchange-worker-default,exchange-worker-batch
priority=999
